### ISSUE TITLE
Uppercase-adjusted : takes priority over :: programming ligature

### ISSUE THREAD

**Issue by luciascarlet** [weiweihuanghuang/fragment-mono#2]
The :: programming ligature is very commonly seen when writing languages like C++ or Rust that use :: as a path/namespacing operator. In these situations, it will often be followed by an uppercase character if it is pointing to an item with an uppercase name (usually a type or class of some kind). When this is the case, the uppercase-adjusted : takes precedence over the :: ligature *only* for the second :, causing it to look "stepped". Removing the "case" feature from the font entirely in Glyphs allows me to produce an example of the expected behaviour, but this is not ideal as it removes the uppercase-adjusted : completely, whereas instead it should remain and simply be overridden by the :: ligature and not the other way round.

Current behaviour:
<img width="724" alt="Current" src="https://user-images.githubusercontent.com/13824526/195900121-7d4de4c7-a509-4a44-9789-5cd5a51d2e57.png">

Expected behaviour (demonstrated by removing "case" feature):
<img width="752" alt="Expected" src="https://user-images.githubusercontent.com/13824526/195900168-0b0d9526-bfa4-4025-8acd-3af287f96eec.png">

**Comment by weiweihuanghuang** [comment]
Thanks for reporting this! That's really good to know, I'll push a fix soon and check for any other situations similar.

**Comment by weiweihuanghuang** [comment]
Fixed :)
