### ISSUE TITLE
Please consider adding a bar to ghyph for number "1"

### ISSUE THREAD

**Issue by Coordinator8763** [weiweihuanghuang/fragment-mono#6]
Fragment Mono is a new discovery for me and I absolutely love it, except for the imbalanced appearance for number 1.

for regular (non-monospace) fonts, the additional gap caused by non-inclusion of bottom bar can be adjusted using kerning, yet for monospace, the gap between 1 and any other letter feels imbalanced. Please consider adding a horizontal bar to 1.

![image](https://github.com/weiweihuanghuang/fragment-mono/assets/114034842/667b80b1-4dfe-4f5d-b5e3-e12ee13d233a)
![image](https://github.com/weiweihuanghuang/fragment-mono/assets/114034842/0e41384b-d1f1-4b2b-a4ac-5e468637bd61)

**Comment by weiweihuanghuang** [comment]
Done. Activate with "stylistic set 07" or `ss07` in CSS.
